### ISSUE TITLE
Operator Version 0.25.0 and 0.25.1 are producing "invalid memory address" error

### ISSUE THREAD

**Issue by karthik-thiyagarajan** [Altinity/clickhouse-operator#1749]
I'm able to see that there are no restarts happening on my operator when i am in 0.24.3 docker tag of clickhouse operator. However i see that the operator restarts multiple times when i am in 0.25.0 or in 0.25.1 version.
```
I0618 10:08:48.319164       1 worker-reconciler-helper.go:52] getHostSoftwareVersion():Need to report version from the tag. Tag: 25.5.2.47 Host: 0-2 
I0618 10:08:48.319391       1 stateful-set-application.go:176] stsSetupLogContainer():clickhouse/clickhouse-server/c25cff67-c577-410a-9ff2-61792518067b:add log container for host: 1-0
I0618 10:08:48.518054       1 statefulset-reconciler.go:108] clickhouse/chi-clickhouse-server-mycluster-02-1-0:Have StatefulSet available, try to perform label-based comparison for sts: clickhouse/chi-clickhouse-server-mycluster-02-1-0
I0618 10:08:48.518090       1 object-status.go:54] GetObjectStatusFromMetas():clickhouse/chi-clickhouse-server-mycluster-02-1-0:cur and new objects ARE DIFFERENT based on object version label: Update of the object is required. Object: clickhouse/chi-clickhouse-server-mycluster-02-1-0. Cur: ff779a51ad47b1fbe51fa094c7970dd6eb2c4935 New: e8327fe75e27492df5fbca057b48dd0e648f4657
I0618 10:08:48.518158       1 worker-reconciler-helper.go:52] getHostSoftwareVersion():Need to report version from the tag. Tag: 25.5.2.47 Host: 1-0 
I0618 10:08:48.518384       1 stateful-set-application.go:176] stsSetupLogContainer():clickhouse/clickhouse-server/c25cff67-c577-410a-9ff2-61792518067b:add log container for host: 1-1
I0618 10:08:48.718331       1 statefulset-reconciler.go:108] clickhouse/chi-clickhouse-server-mycluster-02-1-1:Have StatefulSet available, try to perform label-based comparison for sts: clickhouse/chi-clickhouse-server-mycluster-02-1-1
I0618 10:08:48.718368       1 object-status.go:54] GetObjectStatusFromMetas():clickhouse/chi-clickhouse-server-mycluster-02-1-1:cur and new objects ARE DIFFERENT based on object version label: Update of the object is required. Object: clickhouse/chi-clickhouse-server-mycluster-02-1-1. Cur: a6230b5c09accdf8f85eb5f8d383b7bf7fe85916 New: 02ec6d3585a01c74dc27b959df0a9c3e10c8c8f8
I0618 10:08:48.718437       1 worker-reconciler-helper.go:52] getHostSoftwareVersion():Need to report version from the tag. Tag: 25.5.2.47 Host: 1-1 
E0618 10:08:48.718564       1 runtime.go:79] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 257 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x16d0ee0, 0x2be93f0})
        /clickhouse-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:75 +0x7c
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x400057b340?})
        /clickhouse-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:49 +0x78
panic({0x16d0ee0?, 0x2be93f0?})
        /usr/local/go/src/runtime/panic.go:791 +0x124
github.com/altinity/clickhouse-operator/pkg/model/k8s.StatefulSetContainerGet(0x0, {0x4000c48c48?, 0x4000c48ca8?, 0x139ef78?})
        /clickhouse-operator/pkg/model/k8s/stateful_set.go:31 +0x80
github.com/altinity/clickhouse-operator/pkg/model/chi/creator.(*ContainerManager).getContainerClickHouse(...)
        /clickhouse-operator/pkg/model/chi/creator/container.go:69
github.com/altinity/clickhouse-operator/pkg/model/chi/creator.(*ContainerManager).getImageTagClickHouse(0x4000c48cb8?, 0x23014?)
        /clickhouse-operator/pkg/model/chi/creator/container.go:79 +0x60
github.com/altinity/clickhouse-operator/pkg/model/chi/creator.(*ContainerManager).GetAppImageTag(0x19e578c?, 0x4000c2ff80?)
        /clickhouse-operator/pkg/model/chi/creator/container.go:46 +0x1c
github.com/altinity/clickhouse-operator/pkg/model/common/creator.(*Creator).GetAppImageTag(0x4000c48cf8?, 0x23284?)
        /clickhouse-operator/pkg/model/common/creator/stateful-set-application.go:186 +0x2c
github.com/altinity/clickhouse-operator/pkg/controller/chi.(*worker).getHostSoftwareVersion(0x4000848600, {0x1ca2ad8, 0x4000c76910}, 0x40012e0b60, {0x0?, 0x10?, 0x80?})
        /clickhouse-operator/pkg/controller/chi/worker-reconciler-helper.go:43 +0x78
github.com/altinity/clickhouse-operator/pkg/controller/chi.(*worker).findMinMaxVersions.func1(0x40012e0b60)
        /clickhouse-operator/pkg/controller/chi/worker-reconciler-chi.go:201 +0x78
github.com/altinity/clickhouse-operator/pkg/apis/clickhouse.altinity.com/v1.(*ClickHouseInstallation).WalkHosts(0x4000ae11e0, 0x4000c49148)
        /clickhouse-operator/pkg/apis/clickhouse.altinity.com/v1/type_chi.go:669 +0x170
github.com/altinity/clickhouse-operator/pkg/controller/chi.(*worker).findMinMaxVersions(0x4000848600?, {0x1ca2ad8?, 0x4000c76910?}, 0x4000ae11e0)
        /clickhouse-operator/pkg/controller/chi/worker-reconciler-chi.go:199 +0x48
github.com/altinity/clickhouse-operator/pkg/controller/chi.(*worker).buildFromMeta(0x4000848600, {0x1ca2ad8, 0x4000c76910}, {0x1cbaf00, 0x40010a0b60}, 0x0)
        /clickhouse-operator/pkg/controller/chi/worker-reconciler-chi.go:171 +0xa8
github.com/altinity/clickhouse-operator/pkg/controller/chi.(*worker).updateFromMeta(0x4000848600, {0x1ca2ad8, 0x4000c76910}, {0x1cbaf00?, 0x40010a0b60?}, 0x78?, {{{0x0, 0x0, 0x1, 0x0, ...}, ...}, ...}, ...)
        /clickhouse-operator/pkg/controller/chi/worker.go:265 +0x38
github.com/altinity/clickhouse-operator/pkg/controller/chi.(*worker).updateEndpoints(...)
        /clickhouse-operator/pkg/controller/chi/worker.go:241
github.com/altinity/clickhouse-operator/pkg/controller/chi.(*worker).processReconcileEndpoints(0x100000003?, {0x1ca2ad8?, 0x4000c76910?}, 0x0?)
        /clickhouse-operator/pkg/controller/chi/worker-boilerplate.go:120 +0xc0
github.com/altinity/clickhouse-operator/pkg/controller/chi.(*worker).processItem(0x4000848600, {0x1ca2ad8, 0x4000c76910}, {0x16f40e0, 0x4000f5cb10})
        /clickhouse-operator/pkg/controller/chi/worker-boilerplate.go:170 +0x3a8
github.com/altinity/clickhouse-operator/pkg/controller/chi.(*worker).run(0x4000848600)
        /clickhouse-operator/pkg/controller/chi/worker-boilerplate.go:53 +0x2b8
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x30?)
        /clickhouse-operator/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:226 +0x40
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x4000c2e8b0, {0x1c838c0, 0x4000b79890}, 0x1, 0x4000656d20)
        /clickhouse-operator/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:227 +0x90
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x4000c2e8b0, 0x3b9aca00, 0x0, 0x1, 0x4000656d20)
        /clickhouse-operator/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:204 +0x80
k8s.io/apimachinery/pkg/util/wait.Until(...)
        /clickhouse-operator/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:161
created by github.com/altinity/clickhouse-operator/pkg/controller/chi.(*Controller).Run in goroutine 99
        /clickhouse-operator/pkg/controller/chi/controller.go:526 +0x4d8
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x238 pc=0x120ffe0]

goroutine 257 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x400057b340?})
        /clickhouse-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:56 +0xe0
panic({0x16d0ee0?, 0x2be93f0?})
        /usr/local/go/src/runtime/panic.go:791 +0x124
github.com/altinity/clickhouse-operator/pkg/model/k8s.StatefulSetContainerGet(0x0, {0x4000c48c48?, 0x4000c48ca8?, 0x139ef78?})
        /clickhouse-operator/pkg/model/k8s/stateful_set.go:31 +0x80
github.com/altinity/clickhouse-operator/pkg/model/chi/creator.(*ContainerManager).getContainerClickHouse(...)
        /clickhouse-operator/pkg/model/chi/creator/container.go:69
github.com/altinity/clickhouse-operator/pkg/model/chi/creator.(*ContainerManager).getImageTagClickHouse(0x4000c48cb8?, 0x23014?)
        /clickhouse-operator/pkg/model/chi/creator/container.go:79 +0x60
github.com/altinity/clickhouse-operator/pkg/model/chi/creator.(*ContainerManager).GetAppImageTag(0x19e578c?, 0x4000c2ff80?)
        /clickhouse-operator/pkg/model/chi/creator/container.go:46 +0x1c
github.com/altinity/clickhouse-operator/pkg/model/common/creator.(*Creator).GetAppImageTag(0x4000c48cf8?, 0x23284?)
        /clickhouse-operator/pkg/model/common/creator/stateful-set-application.go:186 +0x2c
github.com/altinity/clickhouse-operator/pkg/controller/chi.(*worker).getHostSoftwareVersion(0x4000848600, {0x1ca2ad8, 0x4000c76910}, 0x40012e0b60, {0x0?, 0x10?, 0x80?})
        /clickhouse-operator/pkg/controller/chi/worker-reconciler-helper.go:43 +0x78
github.com/altinity/clickhouse-operator/pkg/controller/chi.(*worker).findMinMaxVersions.func1(0x40012e0b60)
        /clickhouse-operator/pkg/controller/chi/worker-reconciler-chi.go:201 +0x78
github.com/altinity/clickhouse-operator/pkg/apis/clickhouse.altinity.com/v1.(*ClickHouseInstallation).WalkHosts(0x4000ae11e0, 0x4000c49148)
        /clickhouse-operator/pkg/apis/clickhouse.altinity.com/v1/type_chi.go:669 +0x170
github.com/altinity/clickhouse-operator/pkg/controller/chi.(*worker).findMinMaxVersions(0x4000848600?, {0x1ca2ad8?, 0x4000c76910?}, 0x4000ae11e0)
        /clickhouse-operator/pkg/controller/chi/worker-reconciler-chi.go:199 +0x48
github.com/altinity/clickhouse-operator/pkg/controller/chi.(*worker).buildFromMeta(0x4000848600, {0x1ca2ad8, 0x4000c76910}, {0x1cbaf00, 0x40010a0b60}, 0x0)
        /clickhouse-operator/pkg/controller/chi/worker-reconciler-chi.go:171 +0xa8
github.com/altinity/clickhouse-operator/pkg/controller/chi.(*worker).updateFromMeta(0x4000848600, {0x1ca2ad8, 0x4000c76910}, {0x1cbaf00?, 0x40010a0b60?}, 0x78?, {{{0x0, 0x0, 0x1, 0x0, ...}, ...}, ...}, ...)
        /clickhouse-operator/pkg/controller/chi/worker.go:265 +0x38
github.com/altinity/clickhouse-operator/pkg/controller/chi.(*worker).updateEndpoints(...)
        /clickhouse-operator/pkg/controller/chi/worker.go:241
github.com/altinity/clickhouse-operator/pkg/controller/chi.(*worker).processReconcileEndpoints(0x100000003?, {0x1ca2ad8?, 0x4000c76910?}, 0x0?)
        /clickhouse-operator/pkg/controller/chi/worker-boilerplate.go:120 +0xc0
github.com/altinity/clickhouse-operator/pkg/controller/chi.(*worker).processItem(0x4000848600, {0x1ca2ad8, 0x4000c76910}, {0x16f40e0, 0x4000f5cb10})
        /clickhouse-operator/pkg/controller/chi/worker-boilerplate.go:170 +0x3a8
github.com/altinity/clickhouse-operator/pkg/controller/chi.(*worker).run(0x4000848600)
        /clickhouse-operator/pkg/controller/chi/worker-boilerplate.go:53 +0x2b8
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x30?)
        /clickhouse-operator/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:226 +0x40
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x4000c2e8b0, {0x1c838c0, 0x4000b79890}, 0x1, 0x4000656d20)
        /clickhouse-operator/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:227 +0x90
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x4000c2e8b0, 0x3b9aca00, 0x0, 0x1, 0x4000656d20)
        /clickhouse-operator/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:204 +0x80
k8s.io/apimachinery/pkg/util/wait.Until(...)
        /clickhouse-operator/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:161
created by github.com/altinity/clickhouse-operator/pkg/controller/chi.(*Controller).Run in goroutine 99
        /clickhouse-operator/pkg/controller/chi/controller.go:526 +0x4d8
```

**Comment by d1ngd0** [comment]
We have been running into something similar, thank you for creating an issue. I was hoping to re-create it with a smaller ClickhouseInstallation manifest to share. We don't run into this issue with smaller clusters, as the problem tends to occur when when spinning up shard 8. We consistently get this with clusters of 18 shards and 2 replicas.

I will try to find some time today to create a smaller manifest to easily replicate the behavior we are seeing.

I can also verify that rolling back to 0.24.5 fixes the issue, as the same manifest works fine at the older version.

**Comment by karthik-thiyagarajan** [comment]
Ours is a 2 cluster setup with 3 shards and 3 replicas in each cluster and we see this issue in this setup consistently. However, it does not occur when i downgraded my operator version to 0.24.3 or 0.24.5 and it works perfectly good. 

It happens in 0.25.0 and 0.25.1 alone

**Comment by alex-zaitsev** [comment]
Hopefully it is fixed by https://github.com/Altinity/clickhouse-operator/pull/1750

@karthik-thiyagarajan , @d1ngd0 
Could you please check if it solves your issue if you are using 0.25.1 already?

**Comment by scottlaird** [comment]
FWIW, I'm seeing the same thing in 0.25, installed via the helm chart.  I don't see a 0.25.1 or newer available via helm, and I don't really want to do an end-run around helm to install from git if I can avoid it.

**Comment by scottlaird** [comment]
I just updated to the newly released 0.25.1, and I'm still seeing a crash:

```
$ kubectl describe deployment.apps/clickhouse-a471db5a-altinity-clickhouse-operator
...
  Containers:
   altinity-clickhouse-operator:
    Image:      altinity/clickhouse-operator:0.25.1
...
$ kubectl logs -f deployment.apps/clickhouse-a471db5a-altinity-clickhouse-operator
...
I0701 16:07:10.839320       1 worker-reconciler-helper.go:52] getHostSoftwareVersion():Host:4-0[4/0]:default/clickhouse:Need to report version from the tag. Tag: latest Host: 4-0 
I0701 16:07:11.038961       1 statefulset-reconciler.go:108] unknown:Have StatefulSet available, try to perform label-based comparison for sts: default/chi-clickhouse-custom-4-1
I0701 16:07:11.039034       1 object-status.go:47] GetObjectStatusFromMetas():unknown:cur and new objects are equal based on object version label. Update of the object is not required. Object: default/chi-clickhouse-custom-4-1
I0701 16:07:11.039171       1 worker-reconciler-helper.go:52] getHostSoftwareVersion():Host:4-1[4/1]:default/clickhouse:Need to report version from the tag. Tag: latest Host: 4-1 
I0701 16:07:11.239408       1 statefulset-reconciler.go:108] unknown:Have StatefulSet available, try to perform label-based comparison for sts: default/chi-clickhouse-custom-4-2
I0701 16:07:11.239498       1 object-status.go:47] GetObjectStatusFromMetas():unknown:cur and new objects are equal based on object version label. Update of the object is not required. Object: default/chi-clickhouse-custom-4-2
E0701 16:07:11.239929       1 runtime.go:79] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 309 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x1bf0140, 0x313f2b0})
	/clickhouse-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:75 +0x85
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x0?})
	/clickhouse-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:49 +0x6b
panic({0x1bf0140?, 0x313f2b0?})
	/usr/local/go/src/runtime/panic.go:791 +0x132
github.com/altinity/clickhouse-operator/pkg/apis/swversion.(*SoftWareVersion).Cmp(...)
	/clickhouse-operator/pkg/apis/swversion/software_version.go:128
github.com/altinity/clickhouse-operator/pkg/apis/clickhouse.altinity.com/v1.(*ClickHouseInstallation).FindMinMaxVersions.func1(0xc00145b040)
	/clickhouse-operator/pkg/apis/clickhouse.altinity.com/v1/type_chi.go:718 +0x32
github.com/altinity/clickhouse-operator/pkg/apis/clickhouse.altinity.com/v1.(*ClickHouseInstallation).WalkHosts(0xc000bc7d40, 0xc0009b1150)
	/clickhouse-operator/pkg/apis/clickhouse.altinity.com/v1/type_chi.go:669 +0x18a
github.com/altinity/clickhouse-operator/pkg/apis/clickhouse.altinity.com/v1.(*ClickHouseInstallation).FindMinMaxVersions(0xc000bc7d40)
	/clickhouse-operator/pkg/apis/clickhouse.altinity.com/v1/type_chi.go:717 +0xb2
github.com/altinity/clickhouse-operator/pkg/controller/chi.(*worker).findMinMaxVersions(0xc00006ca00?, {0x21c3238?, 0xc0013c00a0?}, 0xc000bc7d40)
	/clickhouse-operator/pkg/controller/chi/worker-reconciler-chi.go:207 +0x4f
github.com/altinity/clickhouse-operator/pkg/controller/chi.(*worker).buildFromMeta(0xc00006ca00, {0x21c3238, 0xc0013c00a0}, {0x21dba80, 0xc001047a00}, 0x0)
	/clickhouse-operator/pkg/controller/chi/worker-reconciler-chi.go:171 +0xea
github.com/altinity/clickhouse-operator/pkg/controller/chi.(*worker).updateFromMeta(0xc00006ca00, {0x21c3238, 0xc0013c00a0}, {0x21dba80?, 0xc001047a00?}, 0xd0?, {{{0x0, 0x0, 0x1, 0x0, ...}, ...}, ...}, ...)
	/clickhouse-operator/pkg/controller/chi/worker.go:265 +0x47
github.com/altinity/clickhouse-operator/pkg/controller/chi.(*worker).updateEndpoints(...)
	/clickhouse-operator/pkg/controller/chi/worker.go:241
github.com/altinity/clickhouse-operator/pkg/controller/chi.(*worker).processReconcileEndpoints(0x100000003?, {0x21c3238?, 0xc0013c00a0?}, 0x0?)
	/clickhouse-operator/pkg/controller/chi/worker-boilerplate.go:120 +0x93
github.com/altinity/clickhouse-operator/pkg/controller/chi.(*worker).processItem(0xc00006ca00, {0x21c3238, 0xc0013c00a0}, {0x1c132c0, 0xc0012cc120})
	/clickhouse-operator/pkg/controller/chi/worker-boilerplate.go:170 +0x4f0
github.com/altinity/clickhouse-operator/pkg/controller/chi.(*worker).run(0xc00006ca00)
	/clickhouse-operator/pkg/controller/chi/worker-boilerplate.go:53 +0x38f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x30?)
	/clickhouse-operator/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:226 +0x33
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc001116570, {0x21a4120, 0xc000c1bc80}, 0x1, 0xc0004aad90)
	/clickhouse-operator/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:227 +0xaf
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc001116570, 0x3b9aca00, 0x0, 0x1, 0xc0004aad90)
	/clickhouse-operator/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:204 +0x7f
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/clickhouse-operator/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:161
created by github.com/altinity/clickhouse-operator/pkg/controller/chi.(*Controller).Run in goroutine 130
	/clickhouse-operator/pkg/controller/chi/controller.go:526 +0x5a5
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xc0e492]

goroutine 309 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x0?})
	/clickhouse-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:56 +0xcd
panic({0x1bf0140?, 0x313f2b0?})
	/usr/local/go/src/runtime/panic.go:791 +0x132
github.com/altinity/clickhouse-operator/pkg/apis/swversion.(*SoftWareVersion).Cmp(...)
	/clickhouse-operator/pkg/apis/swversion/software_version.go:128
github.com/altinity/clickhouse-operator/pkg/apis/clickhouse.altinity.com/v1.(*ClickHouseInstallation).FindMinMaxVersions.func1(0xc00145b040)
	/clickhouse-operator/pkg/apis/clickhouse.altinity.com/v1/type_chi.go:718 +0x32
github.com/altinity/clickhouse-operator/pkg/apis/clickhouse.altinity.com/v1.(*ClickHouseInstallation).WalkHosts(0xc000bc7d40, 0xc0009b1150)
	/clickhouse-operator/pkg/apis/clickhouse.altinity.com/v1/type_chi.go:669 +0x18a
github.com/altinity/clickhouse-operator/pkg/apis/clickhouse.altinity.com/v1.(*ClickHouseInstallation).FindMinMaxVersions(0xc000bc7d40)
	/clickhouse-operator/pkg/apis/clickhouse.altinity.com/v1/type_chi.go:717 +0xb2
github.com/altinity/clickhouse-operator/pkg/controller/chi.(*worker).findMinMaxVersions(0xc00006ca00?, {0x21c3238?, 0xc0013c00a0?}, 0xc000bc7d40)
	/clickhouse-operator/pkg/controller/chi/worker-reconciler-chi.go:207 +0x4f
github.com/altinity/clickhouse-operator/pkg/controller/chi.(*worker).buildFromMeta(0xc00006ca00, {0x21c3238, 0xc0013c00a0}, {0x21dba80, 0xc001047a00}, 0x0)
	/clickhouse-operator/pkg/controller/chi/worker-reconciler-chi.go:171 +0xea
github.com/altinity/clickhouse-operator/pkg/controller/chi.(*worker).updateFromMeta(0xc00006ca00, {0x21c3238, 0xc0013c00a0}, {0x21dba80?, 0xc001047a00?}, 0xd0?, {{{0x0, 0x0, 0x1, 0x0, ...}, ...}, ...}, ...)
	/clickhouse-operator/pkg/controller/chi/worker.go:265 +0x47
github.com/altinity/clickhouse-operator/pkg/controller/chi.(*worker).updateEndpoints(...)
	/clickhouse-operator/pkg/controller/chi/worker.go:241
github.com/altinity/clickhouse-operator/pkg/controller/chi.(*worker).processReconcileEndpoints(0x100000003?, {0x21c3238?, 0xc0013c00a0?}, 0x0?)
	/clickhouse-operator/pkg/controller/chi/worker-boilerplate.go:120 +0x93
github.com/altinity/clickhouse-operator/pkg/controller/chi.(*worker).processItem(0xc00006ca00, {0x21c3238, 0xc0013c00a0}, {0x1c132c0, 0xc0012cc120})
	/clickhouse-operator/pkg/controller/chi/worker-boilerplate.go:170 +0x4f0
github.com/altinity/clickhouse-operator/pkg/controller/chi.(*worker).run(0xc00006ca00)
	/clickhouse-operator/pkg/controller/chi/worker-boilerplate.go:53 +0x38f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x30?)
	/clickhouse-operator/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:226 +0x33
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc001116570, {0x21a4120, 0xc000c1bc80}, 0x1, 0xc0004aad90)
	/clickhouse-operator/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:227 +0xaf
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc001116570, 0x3b9aca00, 0x0, 0x1, 0xc0004aad90)
	/clickhouse-operator/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:204 +0x7f
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/clickhouse-operator/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:161
created by github.com/altinity/clickhouse-operator/pkg/controller/chi.(*Controller).Run in goroutine 130
	/clickhouse-operator/pkg/controller/chi/controller.go:526 +0x5a5
```

**Comment by zeev1079** [comment]
Facing the same issue, have upgraded the operator from `0.23.6` to `0.24.5`, it works fine, but from `0.24.5 or 0.23.6` to `0.25.0 or 0.25.1 or 0.25.2`, it fails with the error above:
```
E0709 14:39:38.851777 1 runtime.go:79] Observed a panic: "invalid memory address or nil pointer dereference"
...
github.com/altinity/clickhouse-operator/pkg/apis/swversion.(*SoftWareVersion).Cmp(...)
...
```
my cluster is 25 shards and 2 replicas for reference

**Comment by Slach** [comment]
@zeev1079 could you share full stacktrace with error for 0.25.2?

**Comment by scottlaird** [comment]
Where does one find 0.25.2?

**Comment by sunsingerus** [comment]
it is a development version, not released yet - but it is available on dockerhub by direct tag

**Comment by zeev1079** [comment]
after upgrading to 0.25.2 the previous panic is gone, but still stuck reconciliation loop and is unable to bring the cluster to a healthy state. looking why..

**Comment by alex-zaitsev** [comment]
@zeev1079 , have you found what's wring with reconciliation loop?

**Comment by scottlaird** [comment]
FWIW, my cluster seems happy with 0.25.2 and it no longer panicking.  It looks like it's finishing its update loop successfully.

**Comment by sunsingerus** [comment]
> FWIW, my cluster seems happy with 0.25.2 and it no longer panicking. It looks like it's finishing its update loop successfully.

Nice! Thanks for letting know! Can release 0.25.2 now :)

**Comment by karthik-thiyagarajan** [comment]
The latest version works for me too. thanks for the fix.
